-- Выполни этот SQL в Supabase SQL Editor.
-- Таблицы для профилей и сообщений.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  city text default '',
  interests text default '',
  created_at timestamptz default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;

create policy "profiles readable by everyone"
on public.profiles for select using (true);

create policy "users insert own profile"
on public.profiles for insert with check (auth.uid() = id);

create policy "users update own profile"
on public.profiles for update using (auth.uid() = id);

create policy "users read own messages"
on public.messages for select
using (auth.uid() = sender_id or auth.uid() = receiver_id);

create policy "users send messages"
on public.messages for insert
with check (auth.uid() = sender_id);
